name: Send Notification to Workplace Chat

on:
  push:
    branches: [test-workflow]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print Hello World
        run: echo Hello World!

      - name: Print Mona
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'

